version: '3.8'

networks:
  proxy:
    external: true

services:
  web:
    build: .
    networks:
      - proxy
    restart: unless-stopped
    env_file:
      - stack.env

  promtail:
    build:
      context: .
      dockerfile: Dockerfile.promtail
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - stack.env
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
